(function(root,factory){const value=factory();if(typeof module==='object'&&module.exports)module.exports=value;else root.MintoI18n=value;})(typeof globalThis==='object'?globalThis:this,function(){
'use strict';
// Keys are exact source strings. Technical model IDs, user content and Japanese character speech are never translated.
const rows=[
['主模型','メインモデル','Primary model'],['主模型支持图片等多模态输入','メインモデルは画像などのマルチモーダル入力に対応','Primary model supports images and multimodal input'],
['勾选后，截图、提问和对话历史直接交给主模型。请根据模型实际能力选择。','選択すると、画像・質問・会話履歴をメインモデルへ直接送ります。実際の対応能力に合わせて選択してください。','When checked, screenshots, questions and conversation history go directly to the primary model. Select according to its actual capabilities.'],
['备用视觉模型（可选）','予備の画像理解モデル（任意）','Backup vision model (optional)'],
['主模型不支持图片，或图片请求被拒绝时使用。鉴权、限流和网络错误不会触发切换。','メインモデルが画像非対応、または画像入力が拒否された場合に使用します。認証・レート制限・通信エラーでは切り替えません。','Used when the primary model does not support images or its image input is rejected. Authentication, rate-limit and network failures do not trigger fallback.'],
['请启用主模型多模态或配置备用视觉模型','メインモデルの画像入力を有効にするか、予備の画像モデルを設定してください','Enable multimodal input on the primary model or configure backup vision'],
['日语发音稿无效','日本語の読み上げ原稿が無効です','Invalid Japanese speech reading'],
['界面与启动','表示と起動','Appearance and startup'],['登录 Windows 时自动启动','Windows ログイン時に起動','Launch at Windows login'],['字体名称','フォント名','Font name'],['字号','文字サイズ','Font size'],
['请输入本机已安装的字体名称；缺失时使用系统备用字体。字号只调整界面文字。','この端末のフォント名を入力してください。未インストールなら代替フォントを使用します。文字サイズは UI のみ変更します。','Enter an installed font name. Missing fonts use a system fallback. Font size changes interface text only.'],
['免安装版启用自启后，请保持程序目录位置不变。','ポータブル版で自動起動を有効にした後は、アプリのフォルダーを移動しないでください。','Keep the portable application folder in place after enabling startup.'],['开机自启仅支持打包后的应用','自動起動は配布版アプリで使用できます','Startup is available in packaged applications only'],
['观察范围','観察範囲','Observation scope'],['整个屏幕','画面全体','Entire display'],['框选区域','選択範囲','Selected region'],['鼠标框选','範囲を選択','Select region'],['选择观察区域','観察範囲を選択','Select observation region'],['拖动鼠标框选，松开保存；Esc 或右键取消','ドラッグして範囲を選択し、離して保存。Esc または右クリックでキャンセル','Drag to select; release to save. Esc or right-click to cancel'],
['尚未选择区域','範囲は未選択です','No region selected'],['已选区域：宽 {width}% · 高 {height}%','選択範囲：幅 {width}% · 高さ {height}%','Selected region: width {width}% · height {height}%'],['观察区域已保存。','観察範囲を保存しました。','Observation region saved.'],
['观察区域无效，请重新框选','観察範囲が無効です。選択し直してください','Invalid observation region; select it again'],['观察区域太小，请重新框选','観察範囲が小さすぎます。選択し直してください','Observation region is too small; select it again'],['框选参数无效','範囲選択のパラメーターが無効です','Invalid region selection parameters'],['正在选择观察区域','観察範囲を選択しています','Observation region selection is already open'],['框选窗口无法打开','範囲選択ウィンドウを開けません','Could not open the region selection window'],['字体名称无效','フォント名が無効です','Invalid font name'],['字号须在 10 到 28 之间','文字サイズは 10～28 にしてください','Font size must be between 10 and 28'],
['界面语言','表示言語','Interface language'],['设置 · 本地保存','設定 · この端末に保存','Settings · Saved locally'],['Minto Assistant · 设置','Minto Assistant · 設定','Minto Assistant · Settings'],
['对话服务','会話サービス','Conversation service'],['填写服务实际提供的完整兼容地址和精确模型 ID。地址需止于 API 基础路径，程序追加 /chat/completions。公开对话和语音使用日语。','サービスの正確な API ベース URL とモデル ID を入力してください。/chat/completions は自動追加されます。ミントの返事と音声は日本語です。','Enter the exact compatible API base URL and model ID. The app appends /chat/completions. Minto’s replies and speech remain Japanese.'],
['服务类型','プロバイダー','Provider'],['精确模型 ID','正確なモデル ID','Exact model ID'],['自定义兼容服务','カスタム互換サービス','Custom compatible service'],['推理强度','推論の強さ','Reasoning effort'],['低 · low','低 · low','Low · low'],['中 · medium','中 · medium','Medium · medium'],['高 · high','高 · high','High · high'],['最大 · max','最大 · max','Maximum · max'],['API 基础地址','API ベース URL','API base URL'],['API 密钥','API キー','API key'],['留空保留已保存密钥','空欄なら保存済みキーを維持','Leave blank to keep the saved key'],['保存并测试连接','保存して接続テスト','Save and test connection'],['清除密钥','キーを削除','Clear key'],
['视觉服务','視覚サービス','Vision service'],['使用独立的视觉配置。测试会读取下方所选屏幕，截图只用于当前请求。','視覚サービスは個別に設定します。テストでは選択した画面を取得し、画像はそのリクエストだけに使用します。','Configure vision separately. Testing captures the selected display; the screenshot is used only for that request.'],
['屏幕观察','画面の観察','Screen observation'],['允许定时观察所选屏幕并主动说话','選択画面を定期的に観察して話しかける','Allow periodic observation and proactive conversation'],['观察屏幕','観察する画面','Display to observe'],['请选择屏幕','画面を選択してください','Select a display'],['观察间隔（秒）','観察間隔（秒）','Observation interval (seconds)'],['主动发话最短间隔（秒）','話しかける最短間隔（秒）','Minimum proactive interval (seconds)'],['锁屏、忙碌、配置不完整、画面未变化或没有适合的话题时暂停发话。托盘菜单也可暂停。','ロック中、会話中、未設定、画面に変化がない場合や話題がない場合は話しかけません。トレイから一時停止できます。','Conversation pauses when locked, busy, incompletely configured, unchanged, or without a suitable topic. You can also pause from the tray.'],['刷新屏幕列表','画面一覧を更新','Refresh displays'],['暂停主动观察','自動観察を一時停止','Pause proactive observation'],['恢复主动观察','自動観察を再開','Resume proactive observation'],
['日语语音与口型','日本語音声と口の動き','Japanese speech and lip sync'],['连接本地 Style-Bert-VITS2 服务。只有实际加载的模型会进入已连接状态；音频振幅驱动口型。','ローカルの Style-Bert-VITS2 に接続します。読み込まれたモデルだけを接続済みとして表示し、音量に合わせて口が動きます。','Connect to local Style-Bert-VITS2. Only loaded models count as connected; audio amplitude drives lip sync.'],['启用语音','音声を有効にする','Enable speech'],['语音运行方式','音声の実行方式','Voice engine'],['内置本地语音模型 · 自动启动','内蔵ローカル音声 · 自動起動','Bundled local voice · Automatic startup'],['外部 Style-Bert-VITS2 服务','外部 Style-Bert-VITS2 サービス','External Style-Bert-VITS2 service'],['语音服务基础地址','音声サービスのベース URL','Voice service base URL'],['模型 ID','モデル ID','Model ID'],['说话人名称','話者名','Speaker name'],['发声风格','音声スタイル','Voice style'],['语速长度系数','音声の長さ倍率','Speech length factor'],['风格权重','スタイルの強さ','Style weight'],['读取已加载模型','読み込み済みモデルを取得','Refresh loaded models'],['导入模型目录','モデルフォルダーを読み込む','Import model folder'],
['角色服装','ミントの衣装','Minto’s outfit'],['当前存档的服装','現在のセーブの衣装','Outfit for the current save'],['日常服','通常服','Everyday outfit'],['睡衣','パジャマ','Pajamas'],
['独立存档','個別セーブ','Independent saves'],['每个存档分别保存完整对话、长期摘要和服装。切换存档会取消正在进行的请求与语音。导出不包含服务配置或 API 密钥。','セーブごとに会話全文、長期要約、衣装を保存します。切り替えると進行中のリクエストと音声を停止します。書き出しに設定や API キーは含みません。','Each save stores full conversations, long-term memory and outfit. Switching cancels ongoing requests and speech. Exports exclude service settings and API keys.'],['存档','セーブ','Save'],['存档名称','セーブ名','Save name'],['长期摘要（完整对话另行保留）','長期要約（会話全文は別途保持）','Long-term summary (full history is retained separately)'],['新建','新規作成','New'],['重命名','名前を変更','Rename'],['切换','切り替え','Switch'],['导出','書き出し','Export'],['导入','読み込み','Import'],['删除','削除','Delete'],['数据目录','データフォルダー','Data folder'],['打开数据目录','データフォルダーを開く','Open data folder'],['保存设置','設定を保存','Save settings'],['密钥由系统加密保存在本机。','キーは OS により暗号化され、この端末に保存されます。','Keys are encrypted by the operating system and saved on this device.'],
['当前配置 {id} · 待读取模型','現在の設定 {id} · モデル未取得','Configured {id} · Models not refreshed'],['自动选择服务首个可用项','利用可能な最初の項目を自動選択','Automatically use the first available item'],['{value} · 未确认','{value} · 未確認','{value} · Unverified'],['已保存 · 留空保留','保存済み · 空欄で維持','Saved · Leave blank to keep'],['尚未保存','未保存','Not saved'],[' · 当前',' · 現在',' · Current'],['运行状态：{status}','実行状態：{status}','Runtime status: {status}'],['完整对话 {count} 条 · 更新于 {date}','会話 {count} 件 · 更新 {date}','Full history: {count} messages · Updated {date}'],['切换后查看此存档的对话数量和摘要。','切り替えると会話件数と要約を表示します。','Switch to this save to view its message count and summary.'],['设置已保存。','設定を保存しました。','Settings saved.'],['有未保存的设置。','未保存の設定があります。','You have unsaved settings.'],['正在测试…','テスト中…','Testing…'],['实际模型：','読み込み済みモデル：','Loaded models: '],['保存后清除','保存時に削除','Will clear when saved'],['请输入存档名称','セーブ名を入力してください','Enter a save name'],['已取消。','キャンセルしました。','Cancelled.'],['存档已导出，不包含 API 密钥。','API キーを含めずにセーブを書き出しました。','Save exported without API keys.'],['存档操作已完成。','セーブ操作が完了しました。','Save operation completed.'],['已读取实际说话人和发声风格。','読み込み済みの話者とスタイルを取得しました。','Loaded speakers and styles refreshed.'],['模型已导入并选中。','モデルを読み込み、選択しました。','Model imported and selected.'],
['尚未连接','未接続','Not connected'],['已连接','接続済み','Connected'],['本地语音已就绪','ローカル音声の準備完了','Local voice ready'],['锁屏暂停','ロック中は一時停止','Paused while locked'],['已暂停','一時停止中','Paused'],['已关闭','無効','Disabled'],['等待配置','設定待ち','Waiting for configuration'],['连接失败，将重试','接続失敗 · 再試行します','Connection failed · Will retry'],['对话或语音中','会話・音声中','Conversation or speech in progress'],['定时观察中','定期観察中','Observing periodically'],['观察状态：','観察状態：','Observation: '],['打开设置','設定を開く','Open settings'],['退出 Minto Assistant','Minto Assistant を終了','Quit Minto Assistant'],['已取消','キャンセル済み','Cancelled'],['取消','キャンセル','Cancel'],['语音服务连接成功','音声サービスに接続しました','Voice service connected'],['连接成功','接続成功','Connected successfully'],['导入 Style-Bert-VITS2 模型目录','Style-Bert-VITS2 モデルフォルダーを読み込む','Import Style-Bert-VITS2 model folder'],['导出独立存档（不含 API 密钥）','セーブを書き出す（API キーを除外）','Export save (without API keys)'],['Minto 存档','Minto セーブ','Minto save'],['导入独立存档','セーブを読み込む','Import save'],['删除存档','セーブを削除','Delete save'],['确认删除此存档的全部对话和摘要？','このセーブの会話全文と要約を削除しますか？','Delete all conversations and the summary in this save?'],
['设置文件版本不支持','未対応の設定ファイルバージョンです','Unsupported settings file version'],['设置格式无效','設定形式が無効です','Invalid settings format'],['未知设置字段','不明な設定項目です','Unknown settings field'],['设置字段类型不匹配','設定項目の型が一致しません','Settings field type mismatch'],['设置字段过长','設定項目が長すぎます','Settings field is too long'],['服务类型无效','プロバイダーが無効です','Invalid provider'],['思考深度无效','推論の強さが無効です','Invalid reasoning effort'],['语音运行方式无效','音声の実行方式が無効です','Invalid voice engine'],['界面语言无效','表示言語が無効です','Invalid interface language'],['服务地址须为 HTTP 或 HTTPS，且不能包含凭据','サービス URL は認証情報を含まない HTTP または HTTPS にしてください','Service URL must use HTTP or HTTPS without embedded credentials'],['观测时间超出范围','観察時間が範囲外です','Observation timing is out of range'],['语音参数超出范围','音声パラメーターが範囲外です','Voice parameter is out of range'],['系统密钥加密不可用，未保存 API 密钥','OS の暗号化が利用できないため API キーを保存しませんでした','Operating system encryption is unavailable; the API key was not saved'],
['来源窗口无效','呼び出し元ウィンドウが無効です','Invalid source window'],['来源页面无效','呼び出し元ページが無効です','Invalid source page'],['请在设置中选择要观察的屏幕','設定で観察する画面を選択してください','Select a display to observe in settings'],['所选屏幕不可用，请重新选择','選択した画面は利用できません。選び直してください','Selected display is unavailable; select it again'],['屏幕截图为空','画面の画像が空です','Screenshot is empty'],['正在处理上一条消息','前のメッセージを処理中です','The previous message is still processing'],['请先配置对话服务','先に会話サービスを設定してください','Configure the conversation service first'],['请先配置视觉服务','先に視覚サービスを設定してください','Configure the vision service first'],['屏幕观察不接受额外参数','画面観察に追加パラメーターは指定できません','Screen observation does not accept extra parameters'],['数据目录操作不接受路径参数','データフォルダー操作にパスは指定できません','Data folder operation does not accept a path'],['连接测试类型无效','接続テストの種類が無効です','Invalid connection test type'],['所选语音模型未加载','選択した音声モデルが読み込まれていません','Selected voice model is not loaded'],['消息格式无效','メッセージ形式が無効です','Invalid message format'],['未知角色服装','不明な衣装です','Unknown outfit'],['存档操作格式无效','セーブ操作の形式が無効です','Invalid save operation format'],['存档 ID 无效','セーブ ID が無効です','Invalid save ID'],['存档名称无效','セーブ名が無効です','Invalid save name'],['存档过大','セーブが大きすぎます','Save is too large'],['未知存档操作','不明なセーブ操作です','Unknown save operation'],['缩放参数无效','拡大縮小のパラメーターが無効です','Invalid scale parameter'],
['随包语音运行时缺失','同梱の音声ランタイムがありません','Bundled voice runtime is missing'],['本地语音启动超时，请查看语音日志','ローカル音声の起動がタイムアウトしました。音声ログを確認してください','Local voice startup timed out; check the voice log'],['无法启动本地语音：','ローカル音声を起動できません：','Could not start local voice: '],['本地语音启动失败，请查看语音日志','ローカル音声を起動できませんでした。音声ログを確認してください','Local voice failed to start; check the voice log'],['本地语音尚未就绪','ローカル音声はまだ準備中です','Local voice is not ready'],['模型验证失败 HTTP ','モデル検証失敗 HTTP ','Model validation failed HTTP '],['请选择包含单个 .safetensors、config.json 和 style_vectors.npy 的模型目录','.safetensors 1 個、config.json、style_vectors.npy を含むモデルフォルダーを選択してください','Select a model folder containing one .safetensors file, config.json and style_vectors.npy'],['模型缺少说话人或风格数据','モデルに話者またはスタイルのデータがありません','Model is missing speaker or style data'],['模型目标目录无效','モデルの保存先が無効です','Invalid model destination folder'],['语音模型列表 HTTP ','音声モデル一覧 HTTP ','Voice model list HTTP '],['语音模型列表格式无效','音声モデル一覧の形式が無効です','Invalid voice model list format'],['语音文本为空','音声用テキストが空です','Speech text is empty'],['所选说话人或发声风格不存在','選択した話者またはスタイルはありません','Selected speaker or style does not exist'],['语音合成 HTTP ','音声合成 HTTP ','Speech synthesis HTTP '],['语音服务未返回 WAV 音频','音声サービスが WAV 音声を返しませんでした','Voice service did not return WAV audio'],
['存档消息附加信息损坏','セーブのメッセージ情報が破損しています','Save message metadata is corrupted'],['存档索引损坏，请从备份恢复。','セーブ一覧が破損しています。バックアップから復元してください。','Save index is corrupted; restore it from a backup.'],['存档不存在','セーブがありません','Save does not exist'],['名称不能为空','名前を空欄にできません','Name cannot be empty'],['不支持的存档格式','未対応のセーブ形式です','Unsupported save format'],['存档对话数据损坏','セーブの会話データが破損しています','Save conversation data is corrupted'],['请在设置中填写服务地址和精确模型 ID。','設定でサービス URL と正確なモデル ID を入力してください。','Enter the service URL and exact model ID in settings.'],['服务地址须为 HTTP 或 HTTPS。','サービス URL は HTTP または HTTPS にしてください。','Service URL must use HTTP or HTTPS.'],['服务未返回标准 Chat Completions 正文','サービスが標準の Chat Completions 本文を返しませんでした','Service did not return standard Chat Completions content'],['视觉模型返回格式无效','視覚モデルの応答形式が無効です','Invalid vision model response format'],['回复为空','返事が空です','Reply is empty'],['回复格式无效','返事の形式が無効です','Invalid reply format'],['回复必须使用日语正文','返事の本文は日本語にしてください','Reply text must be Japanese'],['回复动作不在已定义清单中','返事の動作が許可された一覧にありません','Reply action is outside the defined list'],['日语验证格式无效','日本語検査の形式が無効です','Invalid Japanese validation format'],['回复未通过独立日语验证','返事が日本語の独立検査に合格しませんでした','Reply did not pass independent Japanese validation']
];
const japaneseRows=[
['ドラッグでサイズ変更','拖动调整大小','Drag to resize'],
['そばにいるのです。','陪在你身边。','Right here with you.'],['閉じる','关闭','Close'],['話したいこと、聞かせてほしいのです。','想聊什么都可以告诉我。','Tell me what’s on your mind.'],['ミントに話しかける…','和ミント说话…','Talk to Minto…'],['送信','发送','Send'],['中止','停止','Stop'],['画面も見る','同时看屏幕','Include screen'],['画面を見る','查看屏幕','Observe screen'],['設定','设置','Settings'],['観察を休む','暂停观察','Pause observation'],['観察を再開','恢复观察','Resume observation'],['ドラッグで移動','拖动以移动','Drag to move'],['小さく','缩小','Smaller'],['話す','聊天','Chat'],['大きく','放大','Larger'],['あなた','你','You'],['少し待ってほしいのです…','请稍等…','Please wait…'],['考えているのです…','正在思考…','Thinking…'],['設定を読み込めませんでした。','无法读取设置。','Could not load settings.'],['送信できませんでした。設定を確認してください。','发送失败，请检查设置。','Could not send. Check your settings.'],['画面を見ているのです…','正在查看屏幕…','Observing the screen…'],['画面を観察できませんでした。設定を確認してください。','无法观察屏幕，请检查设置。','Could not observe the screen. Check your settings.'],['会話の要約を更新できませんでした。','无法更新对话摘要。','Could not update the conversation summary.'],['中止しました。','已停止。','Stopped.'],['接続できませんでした。設定を確認してください。','连接失败，请检查设置。','Could not connect. Check your settings.'],['画面を観察できませんでした。','无法观察屏幕。','Could not observe the screen.'],['接続設定を確認してください。','请检查连接设置。','Check your connection settings.'],['音声を再生できませんでした。','无法播放语音。','Could not play speech.'],['ミントを読み込めませんでした。設定を確認してください。','无法加载ミント，请检查设置。','Could not load Minto. Check your settings.']
];
const catalogs={'zh-CN':{},ja:{},en:{}};
for(const [source,ja,en]of rows){catalogs['zh-CN'][source]=source;catalogs.ja[source]=ja;catalogs.en[source]=en;}
for(const [source,zh,en]of japaneseRows){catalogs['zh-CN'][source]=zh;catalogs.ja[source]=source;catalogs.en[source]=en;}
for(const value of Object.values(catalogs))Object.freeze(value);Object.freeze(catalogs);
const languages=Object.freeze(['zh-CN','ja','en']);
function translate(language,source,values={}){const catalog=catalogs[language]||catalogs['zh-CN'];const text=Object.hasOwn(catalog,source)?catalog[source]:source;return text.replace(/\{([a-z]+)\}/g,(match,key)=>Object.hasOwn(values,key)?String(values[key]):match);}
const errorKeys=Object.keys(catalogs['zh-CN']).sort((a,b)=>b.length-a.length);
const compoundPrefixes=['模型验证失败 HTTP ','语音模型列表 HTTP ','语音合成 HTTP ','无法启动本地语音：','实际模型：'];
function localizeError(language,value){
 let text=String(value);if(text.includes('\n'))return text.split('\n').map(line=>localizeError(language,line)).join('\n');
 for(const sourceLanguage of languages){const prefix=translate(sourceLanguage,'运行状态：{status}',{status:''});if(text.startsWith(prefix))return translate(language,'运行状态：{status}',{status:localizeError(language,text.slice(prefix.length))});}
 for(const key of errorKeys)if(Object.values(catalogs).some(catalog=>catalog[key]===text))return translate(language,key);
 // Reverse only these exact, declared UI/error prefixes; leave provider IDs and OS diagnostic suffixes intact.
 for(const key of compoundPrefixes)for(const sourceLanguage of languages){const prefix=translate(sourceLanguage,key);if(text.startsWith(prefix))return translate(language,key)+text.slice(prefix.length);}
 for(const key of errorKeys)if(text.includes(key))text=text.split(key).join(translate(language,key));return text;
}
const documents=new WeakMap();
function apply(document,language){
 let nodes=documents.get(document);if(!nodes){nodes=[];const walker=document.createTreeWalker(document.documentElement,4);let node;while((node=walker.nextNode())){if(['SCRIPT','STYLE'].includes(node.parentElement?.tagName))continue;const source=node.nodeValue.trim();if(Object.hasOwn(catalogs['zh-CN'],source))nodes.push({node,source,prefix:node.nodeValue.match(/^\s*/)[0],suffix:node.nodeValue.match(/\s*$/)[0]});}for(const element of document.querySelectorAll('[title],[placeholder],[aria-label]'))for(const attribute of ['title','placeholder','aria-label'])if(element.hasAttribute(attribute)){const source=element.getAttribute(attribute);if(Object.hasOwn(catalogs['zh-CN'],source))nodes.push({node:element,source,attribute});}documents.set(document,nodes);}
 for(const item of nodes)if(item.attribute)item.node.setAttribute(item.attribute,translate(language,item.source));else item.node.nodeValue=item.prefix+translate(language,item.source)+item.suffix;
 document.documentElement.lang=languages.includes(language)?language:'zh-CN';
}
return Object.freeze({catalogs,languages,translate,localizeError,apply});
});
