'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const i18n=require('../i18n');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
class Node {
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.value='';this.type='';this.checked=false;this.hidden=false;this.disabled=false;this.dataset={};this.listeners={};this.textContent='';}
 append(...nodes){for(const node of nodes)node.owner=this;this.children.push(...nodes);} appendChild(node){this.append(node);return node;} replaceChildren(...nodes){this.children=[];this.append(...nodes);} get options(){return this.children;} get firstElementChild(){return this.children[0];} remove(){this.owner.children.splice(this.owner.children.indexOf(this),1);} focus(){} setPointerCapture(){} addEventListener(name,callback){this.listeners[name]=callback;}
}
function documentFor(html){
 const nodes=new Map();for(const match of html.matchAll(/<([a-z]+)[^>]*\bid="([^"]+)"[^>]*>/g)){const node=new Node(match[1]);node.id=match[2];node.type=match[0].match(/\btype="([^"]+)"/)?.[1]||'';nodes.set(node.id,node);}
 return {nodes,documentElement:{style:{setProperty(){}}},getElementById:id=>nodes.get(id),createElement:tag=>new Node(tag),querySelectorAll:()=>[],addEventListener(){}};
}
function settings(){return {ui:{language:'zh-CN',theme:'system',launch_at_login:false,font_family:'Microsoft YaHei',font_size:14},relationship:{daily_positive_limit:20},llm:{provider:'OpenAI',api_base:'',model:'',reasoning_effort:'high',multimodal:false,key_configured:false},vision:{provider:'OpenAI',api_base:'',model:'',reasoning_effort:'high',key_configured:false},voice:{enabled:false,engine:'bundled',api_base:'',model_id:'0',speaker_name:'',style:'',length:1,style_weight:1},observation:{enabled:false,display_id:'',interval_seconds:60,cooldown_seconds:120,capture_mode:'screen',region_x:0,region_y:0,region_width:0,region_height:0},agent:{enabled:true,working_directory:'D:/Exact',max_steps:12,command_timeout_seconds:60,mcp_servers_json:'[{"id":"ExactID","transport":"http","url":"https://example.com/mcp","headers":{"Authorization":"__MINTO_KEEP_SECRET__"}}]',skill_directories_json:'["D:/Skills"]'}};}
function state(){return {settings:settings(),startupAvailable:true,dataRoot:'D:/Data',paused:false,voiceStatus:'已关闭',save:{id:'save-1',name:'One',updatedAt:'now',skin:'normal',summary:'',messages:[],relationship:{score:60}},saves:[{id:'save-1',name:'One',active:true}],skins:[],observation:{status:'已关闭',detail:''},relationshipStage:'温暖',busy:false,busyAudio:false};}
async function renderer(file,overrides={}){
 const document=documentFor(read(file.replace('.js','.html'))),events={},value=state();
 const api={state:async()=>value,onState:callback=>events.state=callback,onReply:callback=>events.reply=callback,onAgent:callback=>events.agent=callback,voiceModels:async()=>({}),displays:async()=>[],settingsSave:async data=>{value.settings=data;return data;},...overrides};
 const context=vm.createContext({document,window:{minto:api,MintoI18n:{...i18n,apply(){}},MintoAppearance:{apply(){}},addEventListener(){}},console});vm.runInContext(read(file),context);await new Promise(resolve=>setImmediate(resolve));return {document,events,api,value,context};
}
test('preload exposes exact agent test, skill import and removable agent event subscription',async()=>{
 let exposed;const calls=[],listeners=new Map();vm.runInNewContext(read('preload.js'),{require:name=>{assert.equal(name,'electron');return {contextBridge:{exposeInMainWorld:(_name,value)=>exposed=value},ipcRenderer:{invoke:async channel=>calls.push(channel),on:(channel,callback)=>listeners.set(channel,callback),removeListener:(channel,callback)=>{assert.equal(listeners.get(channel),callback);listeners.delete(channel);}}};}});
 assert.equal(typeof exposed.agentTest,'function');assert.equal(typeof exposed.skillImport,'function');assert.equal(typeof exposed.onAgent,'function');await exposed.agentTest();await exposed.skillImport();assert.deepEqual(calls,['minto:agent-test','minto:skill-import']);let received;const off=exposed.onAgent(value=>received=value),payload={status:'done'};listeners.get('minto:agent-event')({},payload);assert.equal(received,payload);off();assert.equal(listeners.size,0);
});
test('agent settings preserve exact masked MCP data and save before capability check',async()=>{
 const calls=[];const app=await renderer('renderer/settings.js',{settingsSave:async data=>{calls.push(data);return data;},agentTest:async()=>{calls.push('test');return {ok:false,tools:['run_command','read_file'],skills:[{name:'Exact',description:'Skill'}],errors:['Connection failed']};}});
 const node=id=>app.document.getElementById(id);assert.ok(node('agent-enabled'));assert.equal(node('agent-working_directory').value,'D:/Exact');node('agent-max_steps').value='25';await node('agent-test').onclick();assert.equal(calls[0].agent.max_steps,25);assert.equal(calls[0].agent.mcp_servers_json,settings().agent.mcp_servers_json);assert.equal(calls[1],'test');assert.match(node('agent-test-status').textContent,/2/);assert.match(node('agent-test-status').textContent,/1/);assert.match(node('agent-test-status').textContent,/Connection failed/);assert.equal(node('agent-test').disabled,false);
});
test('skill import saves current edits then refreshes imported skill directory configuration',async()=>{
 const calls=[],next=state();next.settings.agent.skill_directories_json='["D:/Imported"]';const app=await renderer('renderer/settings.js',{settingsSave:async data=>{calls.push('save');return data;},skillImport:async()=>{calls.push('import');return {cancelled:false,name:'Exact skill'};}});app.api.state=async()=>next;await app.document.getElementById('agent-skill-import').onclick();assert.deepEqual(calls,['save','import']);assert.equal(app.document.getElementById('agent-skill_directories_json').value,'["D:/Imported"]');assert.match(app.document.getElementById('agent-test-status').textContent,/Exact skill/);
});
test('chat safely renders bounded collapsible tool activity and preserves it across state broadcasts',async()=>{
 const app=await renderer('renderer/chat.js'),container=app.document.getElementById('agent-activity');assert.ok(container);app.events.agent({status:'start'});app.events.agent({status:'tool-start',tool:'run_command',step:1,input:{command:'<img src=x onerror=alert(1)>'}});app.events.agent({status:'tool-result',tool:'run_command',step:1,output:'<script>unsafe</script>',isError:true});assert.equal(container.hidden,false);assert.equal(container.children[0].tagName,'DETAILS');assert.match(container.children[0].children[1].textContent,/<img/);assert.match(container.children[1].children[1].textContent,/<script>/);const first=container.children[0];app.events.state(app.value);assert.equal(container.children[0],first);
 for(let step=2;step<105;step++)app.events.agent({status:'tool-start',tool:'read_file',step,input:{path:'D:/Exact'}});assert.equal(container.children.length,100);app.events.agent({status:'done'});assert.equal(container.children.length,100);app.events.state({...app.value,save:{...app.value.save,id:'save-2'}});assert.equal(container.children.length,0);assert.equal(container.hidden,true);app.events.agent({status:'tool-start',tool:'run_command',input:{}});app.events.agent({status:'start'});assert.equal(container.children.length,0);
});
test('agent controls and lifecycle labels are translated in Japanese and English',()=>{
 for(const source of ['工具与技能','启用工具调用','高级工具设置','工作目录','最大执行步数','命令超时（秒）','MCP 服务器 JSON','技能目录 JSON','保存并检查工具与技能','导入技能目录','工具活动','正在使用工具','工具执行完成','工具执行已停止','工具执行失败','第 {step} 步 · {tool}','工具返回 · {tool}','工具错误 · {tool}','已连接工具 {tools} 个 · 已读取技能 {skills} 个','技能已导入：{name}'])for(const language of ['ja','en'])assert.notEqual(i18n.translate(language,source),source,source);
});
test('tool settings keep enable and working directory visible while advanced controls start collapsed',()=>{
 const html=read('renderer/settings.html'),section=html.match(/<section><h2>工具与技能<\/h2>[\s\S]*?<\/section>/)?.[0]||'';
 assert.ok(section.startsWith('<section><h2>工具与技能</h2>'));const advanced=section.match(/<details id="agent-advanced">([\s\S]*?)<\/details>/);assert.ok(advanced);assert.ok(advanced[1].includes('<summary>高级工具设置</summary>'));for(const id of ['agent-max_steps','agent-command_timeout_seconds','agent-mcp_servers_json','agent-skill_directories_json','agent-test','agent-skill-import'])assert.ok(advanced[1].includes('id="'+id+'"'),id);for(const id of ['agent-enabled','agent-working_directory'])assert.ok(section.slice(0,advanced.index).includes('id="'+id+'"'),id);assert.equal(section.includes('代理'),false);
});
test('expanded tool details remain open as later tool events and language changes arrive',async()=>{
 const app=await renderer('renderer/chat.js'),container=app.document.getElementById('agent-activity');app.events.agent({status:'tool-start',tool:'run_command',step:1,input:{command:'echo test'}});container.children[0].open=true;app.events.agent({status:'tool-result',tool:'run_command',step:1,output:'test'});assert.equal(container.children[0].open,true);app.events.state({...app.value,settings:{...app.value.settings,ui:{...app.value.settings.ui,language:'en'}}});assert.equal(container.children[0].open,true);assert.match(container.children[0].children[0].textContent,/Step 1/);
});
test('capability check errors remain visible when the UI language changes',async()=>{
 const app=await renderer('renderer/settings.js',{agentTest:async()=>({ok:false,tools:[],skills:[],errors:['Exact diagnostic']})}),node=id=>app.document.getElementById(id);await node('agent-test').onclick();app.events.state({...app.value,settings:{...app.value.settings,ui:{...app.value.settings.ui,language:'en'}}});assert.match(node('agent-test-status').textContent,/Exact diagnostic/);
});
test('exact agent configuration errors and skill diagnostics localize without altering identifiers',()=>{
 for(const source of ['Agent 工作目录不存在','Agent 检查不接受额外参数','同名技能已存在','技能导入不支持链接','工具调用格式无效','模型输出被截断，未执行工具'])for(const language of ['ja','en'])assert.notEqual(i18n.translate(language,source),source,source);
 for(const source of ['MCP 配置必须为最多 20 个服务器的 JSON 数组','MCP 服务器 ID 无效或重复','MCP 配置包含未知字段','MCP stdio 命令与参数无效','MCP HTTP 地址无效','MCP 传输方式无效','MCP 环境变量或请求头格式无效','Agent 步数或命令超时超出范围','Skill 目录必须为路径字符串的 JSON 数组','MCP 保留凭据不存在','Agent 单次工具调用过多'])for(const language of ['ja','en'])assert.notEqual(i18n.translate(language,source),source,source);
 for(const source of ['Command timed out','MCP tool limit exceeded','SKILL.md YAML frontmatter is missing','Skill name or description is invalid','Skill resource is outside its directory'])for(const language of ['zh-CN','ja'])assert.notEqual(i18n.translate(language,source),source,source);
 assert.equal(i18n.localizeError('zh-CN','Skill not found: Exact_SKILL'),'技能不存在：Exact_SKILL');assert.equal(i18n.localizeError('ja','Unknown MCP tool: mcp_1'),'不明な MCP ツール：mcp_1');
});
