'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const vm=require('node:vm');const http=require('node:http');const {EventEmitter}=require('node:events');const {createRequire}=require('node:module');const {pathToFileURL}=require('node:url');
async function desktop(t,{lockGranted=true}={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'minto-integration-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const handlers=new Map(),windows=[],messages=[],openedPaths=[],popups=[],lockState={paths:[],attempts:0,quits:0};class Window extends EventEmitter{constructor(){super();this.webContents=new EventEmitter();this.webContents.send=(channel,value)=>messages.push({channel,value});this.webContents.setWindowOpenHandler=()=>{};this.webContents.session={setPermissionRequestHandler(){}};windows.push(this);}static fromWebContents(contents){return windows.find(window=>window.webContents===contents);}isDestroyed(){return false;}loadFile(){}setContentProtection(){}getBounds(){return {x:0,y:0,width:700,height:660};}getPosition(){return [0,0];}setPosition(){}setSize(){}setResizable(){}}
const electron={app:Object.assign(new EventEmitter(),{isPackaged:false,whenReady:()=>Promise.resolve(),setPath(name,file){lockState.paths.push([name,file]);},requestSingleInstanceLock:()=>{lockState.attempts++;return lockGranted;},quit(){lockState.quits++;}}),net:{fetch},BrowserWindow:Window,ipcMain:Object.assign(new EventEmitter(),{handle:(channel,handler)=>handlers.set(channel,handler)}),Tray:class extends EventEmitter{setToolTip(){}setContextMenu(){}destroy(){}},Menu:{buildFromTemplate:items=>({items,popup:options=>popups.push({items,options})})},dialog:{},shell:{openPath:async file=>{openedPaths.push(file);return '';}},screen:{getPrimaryDisplay:()=>({id:41,label:'Actual primary display',workArea:{x:0,y:0,width:1920,height:1080}}),getAllDisplays:()=>[{id:41,label:'Actual primary display'}]},desktopCapturer:{getSources:async()=>[]},powerMonitor:new EventEmitter(),safeStorage:{isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from([...s].reverse().join('')),decryptString:b=>[...b.toString()].reverse().join('')}};
const filename=path.join(__dirname,'../main.js'),realRequire=createRequire(filename);const context=vm.createContext({require:name=>name==='electron'?electron:name==='./services/voice-runtime'?{VoiceRuntime:class{start(){return Promise.resolve('http://127.0.0.1:5000');}config(value){return value;}stop(){}}}:realRequire(name),__dirname:path.dirname(filename),process:{argv:[],env:{MINTO_DATA_DIR:root}},console,Buffer,URL,AbortController,setTimeout,clearTimeout,setInterval:()=>1,clearInterval(){}});vm.runInContext(fs.readFileSync(filename,'utf8'),context);await new Promise(resolve=>setImmediate(resolve));const event={sender:windows[0]?.webContents,senderFrame:{url:pathToFileURL(path.join(path.dirname(filename),'renderer/index.html')).href}};return {call:(channel,data)=>handlers.get('minto:'+channel)(event,data),send:(channel,data)=>electron.ipcMain.emit('minto:'+channel,event,data),messages,context,electron,root,openedPaths,popups,windows,lockState};}
test('switching saves cancels a live request and prevents stale reply/history/audio',async t=>{let entered;const entry=new Promise(resolve=>entered=resolve);let finish;const server=http.createServer((request,response)=>{request.resume();entered();finish=()=>{response.writeHead(200,{'Content-Type':'application/json'});response.end(JSON.stringify({choices:[{message:{content:JSON.stringify({text:'こんにちはなのです。',emotion:'happy',pose:'mPose3'})}}]}));};});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>{server.closeAllConnections();server.close();});const app=await desktop(t);await app.call('settings-save',{llm:{api_base:'http://127.0.0.1:'+server.address().port+'/v1',model:'Exact_Model'},voice:{enabled:false}});const initial=await app.call('state');await app.call('chat',{text:'你好',observe:false});await entry;const created=await app.call('save-action',{action:'create',name:'第二存档'});finish();await new Promise(resolve=>setTimeout(resolve,60));const state=await app.call('state');assert.notEqual(state.save.id,initial.save.id);assert.equal(state.save.id,created.save.id);assert.equal(state.save.messages.length,0);assert.equal(state.busy,false);assert.equal(app.messages.some(item=>item.channel==='minto:reply'&&item.value.status==='done'),false);assert.equal(app.messages.some(item=>item.channel==='minto:audio'),false);assert.ok(app.messages.some(item=>item.channel==='minto:audio-stop'));});
test('bridge rejects unexpected sender frames and malformed chat without starting work',async t=>{const app=await desktop(t);await assert.rejects(()=>app.call('chat',{text:'你好',observe:false,image:'untrusted'}));const state=await app.call('state');assert.equal(state.busy,false);assert.equal(state.save.messages.length,0);});
test('audio playback blocks proactive capture and cancel resets playback state',async t=>{const app=await desktop(t);let captures=0;app.electron.desktopCapturer.getSources=async()=>{captures++;return [];};vm.runInContext("settings.update({llm:{api_base:'http://127.0.0.1:1',model:'Exact'},vision:{api_base:'http://127.0.0.1:1',model:'Exact'}})",app.context);app.send('playback-status',true);assert.equal((await app.call('state')).busyAudio,true);await vm.runInContext('observe()',app.context);assert.equal(captures,0);app.send('playback-status','true');assert.equal((await app.call('state')).busyAudio,true);await app.call('cancel');assert.equal((await app.call('state')).busyAudio,false);});
test('data directory bridge opens only its configured directory and rejects payload paths',async t=>{const app=await desktop(t);const state=await app.call('state');assert.equal(state.dataRoot,app.root);await app.call('open-data-directory');assert.deepEqual(app.openedPaths,[app.root]);await assert.rejects(()=>app.call('open-data-directory','C:\\Windows'));assert.deepEqual(app.openedPaths,[app.root]);});
test('new settings observe the actual primary display and character context menu uses tray actions',async t=>{const app=await desktop(t);const state=await app.call('state');assert.equal(state.settings.observation.enabled,true);assert.equal(state.settings.observation.display_id,'41');app.windows[0].webContents.emit('context-menu',{});assert.equal(app.popups.length,1);assert.deepEqual(Array.from(app.popups[0].items,item=>item.label).filter(Boolean),['观察状态：等待配置','打开设置','暂停主动观察','退出 Minto Assistant']);});
test('manual screen observation works without chat text and persists only evidenced summary',async t=>{const seen=[];const server=http.createServer((request,response)=>{let body='';request.on('data',chunk=>body+=chunk);request.on('end',()=>{const input=JSON.parse(body);seen.push(input);const content=typeof input.messages[0].content==='string'&&input.messages[0].content.startsWith('公開本文の言語を検査します。')?JSON.stringify({japanese:true}):Array.isArray(input.messages[0].content)?JSON.stringify({summary:'画面には文書が表示されています。',speak:false}):JSON.stringify({text:'文書を読んでいるのですね。',emotion:'gentle',pose:'mPose0'});response.writeHead(200,{'Content-Type':'application/json'});response.end(JSON.stringify({choices:[{message:{content}}]}));});});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>{server.closeAllConnections();server.close();});const app=await desktop(t);const endpoint='http://127.0.0.1:'+server.address().port+'/v1';await app.call('settings-save',{llm:{api_base:endpoint,model:'Exact_Chat'},vision:{api_base:endpoint,model:'Exact_Vision'},voice:{enabled:false}});app.electron.desktopCapturer.getSources=async()=>[{display_id:'41',thumbnail:{isEmpty:()=>false,toJPEG:()=>Buffer.from('private-screen-frame')}}];await app.call('observe-now');for(let i=0;i<100;i++){if((await app.call('state')).save.messages.length===2)break;await new Promise(resolve=>setTimeout(resolve,10));}const state=await app.call('state');assert.equal(state.save.messages.length,2);const metadata=state.save.messages[1].metadata;assert.equal(metadata.screenSummary,'画面には文書が表示されています。');assert.match(metadata.observedAt,/^\d{4}-\d{2}-\d{2}T/);assert.equal(metadata.display_id,'41');assert.equal(JSON.stringify(state.save).includes(Buffer.from('private-screen-frame').toString('base64')),false);assert.ok(seen[1].messages[0].content.includes(metadata.screenSummary));});

test('a failed periodic vision request retries the same screen on the next observation',async t=>{
 let requests=0;const server=http.createServer((request,response)=>{request.resume();requests++;response.writeHead(503);response.end('temporary failure');});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>{server.closeAllConnections();server.close();});
 const app=await desktop(t),endpoint='http://127.0.0.1:'+server.address().port+'/v1';
 await app.call('settings-save',{llm:{api_base:endpoint,model:'Exact_Chat'},vision:{api_base:endpoint,model:'Exact_Vision'},voice:{enabled:false}});
 app.electron.desktopCapturer.getSources=async()=>[{display_id:'41',thumbnail:{isEmpty:()=>false,toJPEG:()=>Buffer.from('same-screen-frame')}}];
 await vm.runInContext('observe()',app.context);await vm.runInContext('observe()',app.context);
 assert.equal(requests,2);assert.equal((await app.call('state')).busy,false);
});
test('same-data-root second instance quits before constructing windows or opening saves',async t=>{
 const app=await desktop(t,{lockGranted:false});assert.equal(app.windows.length,0);assert.equal(app.lockState.quits,1);assert.equal(app.lockState.attempts,1);
 assert.deepEqual(app.lockState.paths,[['userData',app.root]]);assert.equal(fs.existsSync(path.join(app.root,'saves','index.json')),false);
});
test('changing UI language persists only UI settings and localizes the native menu without cancelling work',async t=>{
 const app=await desktop(t);await app.call('settings-save',{llm:{model:'Exact_Model'},voice:{enabled:false}});app.send('playback-status',true);
 await app.call('language','en');let state=await app.call('state');assert.equal(state.settings.ui.language,'en');assert.equal(state.settings.llm.model,'Exact_Model');assert.equal(state.busyAudio,true);
 app.windows[0].webContents.emit('context-menu',{});assert.deepEqual(Array.from(app.popups.at(-1).items,item=>item.label).filter(Boolean),['Observation: Waiting for configuration','Open settings','Pause proactive observation','Quit Minto Assistant']);
 await app.call('language','ja');app.windows[0].webContents.emit('context-menu',{});assert.deepEqual(Array.from(app.popups.at(-1).items,item=>item.label).filter(Boolean),['観察状態：設定待ち','設定を開く','自動観察を一時停止','Minto Assistant を終了']);
 assert.equal(JSON.parse(fs.readFileSync(path.join(app.root,'settings.json'),'utf8')).ui.language,'ja');await assert.rejects(()=>app.call('language','EN'));
});
test('voice model service errors use the selected interface language',async t=>{
 const server=http.createServer((request,response)=>{request.resume();response.writeHead(200,{'Content-Type':'application/json'});response.end('[]');});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>{server.closeAllConnections();server.close();});
 const app=await desktop(t);await app.call('settings-save',{voice:{engine:'external',api_base:'http://127.0.0.1:'+server.address().port}});
 for(const [language,message]of [['en','Invalid voice model list format'],['ja','音声モデル一覧の形式が無効です']]){await app.call('language',language);await assert.rejects(()=>app.call('voice-models'),error=>error.message===message);}
});
