'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
function load(file){try{return require(file);}catch(e){if(e.code==='MODULE_NOT_FOUND'&&e.message.includes(file))return {};throw e;}}
const {SettingsStore}=load('../services/settings-store');const vm=require('node:vm');const sandbox={window:{addEventListener(){}},module:{exports:{}},console};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../renderer/pet-controller.js'),'utf8'),sandbox);const {sampleCurve,sampleMotion,pointInMesh,splitSpeech,toLayerPoint,gazeForPoint,motionWeight,validateReplyAction}=sandbox.module.exports;
test('desktop contracts exist',()=>{assert.equal(typeof SettingsStore,'function');assert.equal(typeof sampleCurve,'function');});
test('settings encrypt keys on disk and never export them',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'minto-desktop-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const secure={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from([...s].reverse().join('')),decryptString:b=>[...b.toString()].reverse().join('')};const store=new SettingsStore(dir,secure);store.update({llm:{provider:'custom',api_base:'https://example.test/v1',model:'Exact_Model',api_key:'secret-123'}});const disk=fs.readFileSync(path.join(dir,'settings.json'),'utf8');assert.ok(!disk.includes('secret-123'));assert.equal(new SettingsStore(dir,secure).value.llm.api_key,'secret-123');assert.ok(!JSON.stringify(store.public()).includes('secret-123'));assert.equal(store.public().llm.key_configured,true);store.update({llm:{model:'Other_Model'}});assert.equal(store.value.llm.api_key,'secret-123');assert.throws(()=>store.update({llm:{api_base:'file:///C:/test'}}));assert.throws(()=>store.update({llm:{MODEL:'bad'}}));});
test('keys are not persisted when encryption is unavailable',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'minto-desktop-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const store=new SettingsStore(dir,{isEncryptionAvailable:()=>false});assert.throws(()=>store.update({llm:{api_key:'secret'}}));});
test('motion curves honor all four Cubism segment types',()=>{assert.equal(sampleCurve([0,0,0,2,10],1),5);assert.equal(sampleCurve([0,2,2,2,8],1),2);assert.equal(sampleCurve([0,2,3,2,8],1),8);assert.ok(Math.abs(sampleCurve([0,0,1,0.3,0,0.7,1,1,1],0.5)-0.5)<0.0001);assert.equal(sampleCurve([0,1,0,2,3],99),3);});
test('motion loop uses duration and distinguishes parts from parameters',()=>{const m={Meta:{Duration:2,Loop:true},Curves:[{Target:'Parameter',Id:'Exact_Param',Segments:[0,0,0,2,10]},{Target:'PartOpacity',Id:'Exact_Part',Segments:[0,0,0,2,1]}]};const result=sampleMotion(m,3);assert.equal(result.parameters.Exact_Param,5);assert.equal(result.parts.Exact_Part,0.5);assert.equal(result.parameters.Exact_Part,undefined);});
test('mesh hit test respects contour triangles instead of rectangular bounds',()=>{const vertices=[0,0,100,0,0,100],indices=[0,1,2];assert.equal(pointInMesh(20,20,vertices,indices),true);assert.equal(pointInMesh(90,90,vertices,indices),false);assert.equal(pointInMesh(-1,5,vertices,indices),false);});
test('speech is split at Japanese boundaries and each chunk is bounded',()=>{const text='こんにちはなのです。'.repeat(30);const chunks=splitSpeech(text);assert.ok(chunks.length>1);assert.equal(chunks.join(''),text);assert.ok(chunks.every(s=>s.length<=100));});
test('window cursor maps into the actual character layer for gaze and alpha hit testing',()=>{const rect={left:336,top:6,width:364,height:648};const point=toLayerPoint(500,300,rect);assert.equal(point.x,164);assert.equal(point.y,294);const gaze=gazeForPoint({x:518,y:232.8},rect);assert.ok(Math.abs(gaze.x)<0.00001);assert.ok(Math.abs(gaze.y)<0.00001);assert.equal(gazeForPoint({x:2000,y:-1000},rect).x,1);});
test('explicit motion fades honor curve overrides and loop does not fade out every cycle',()=>{const motion={Meta:{Duration:2,Loop:false},FadeInTime:1,FadeOutTime:0.5};assert.equal(motionWeight({},motion,0.5),0.5);assert.ok(Math.abs(motionWeight({},motion,1.75)-0.5)<0.00001);assert.equal(motionWeight({},motion,2.5),0);assert.equal(motionWeight({FadeInTime:0,FadeOutTime:0},motion,1),1);assert.equal(motionWeight({}, {...motion,Meta:{Duration:2,Loop:true}},3),1);});
test('actual original face and pose independently control eyes and hands on both skins',()=>{const skins=JSON.parse(fs.readFileSync(path.join(__dirname,'../assets/skins.json'),'utf8'));for(const skin of skins){const base=path.dirname(path.resolve(__dirname,'../renderer',skin.file));const face=JSON.parse(fs.readFileSync(path.join(base,skin.motions.mFace003_egao),'utf8'));const pose=JSON.parse(fs.readFileSync(path.join(base,skin.motions.mPose3),'utf8'));const expression=sampleMotion(face,1).parameters;assert.equal(expression.ParamEyeMaxOpen,0);assert.equal(expression.ParamEyePhysics,1);const action=sampleMotion(pose,0.5).parameters;assert.ok(Object.hasOwn(action,'ParamLeftHand'));assert.ok(Object.hasOwn(action,'ParamRightHand'));const surprise=JSON.parse(fs.readFileSync(path.join(base,skin.motions.mFace016_odoroki2),'utf8'));const ears=sampleMotion(surprise,0.5).parameters;assert.ok(ears.ParamLeftEar>0.8);assert.ok(ears.ParamRightEar>0.8);}});
test('renderer action validation accepts only service enums and actual skin motions',()=>{const {EMOTIONS,POSES}=require('../services/assistant-service');const motions=JSON.parse(fs.readFileSync(path.join(__dirname,'../assets/skins.json'),'utf8'))[0].motions;assert.equal(validateReplyAction({emotion:'happy',pose:'mPose3'},EMOTIONS,POSES,motions),true);assert.equal(validateReplyAction({emotion:'outside-list',pose:'mPose3'},EMOTIONS,POSES,motions),false);assert.equal(validateReplyAction({emotion:'happy',pose:'outside-list'},EMOTIONS,POSES,motions),false);assert.equal(validateReplyAction({emotion:'happy',pose:'mPose3'},EMOTIONS,POSES,{}),false);assert.equal(validateReplyAction(null,EMOTIONS,POSES,motions),false);});
test('chat and settings expose manual screen observation and fixed data directory entry',()=>{const chat=fs.readFileSync(path.join(__dirname,'../renderer/chat.html'),'utf8'),settings=fs.readFileSync(path.join(__dirname,'../renderer/settings.html'),'utf8');assert.ok(chat.includes('id="observe-screen-button"'));assert.ok(settings.includes('id="data-directory-path"'));assert.ok(settings.includes('id="open-data-directory"'));});
test('network service calls use Electron proxy aware fetch and settings expose exact reasoning and engine fields',()=>{const main=fs.readFileSync(path.join(__dirname,'../main.js'),'utf8'),html=fs.readFileSync(path.join(__dirname,'../renderer/settings.html'),'utf8');assert.ok(main.includes('net.fetch(input,options)'));assert.ok(html.includes('id="llm-reasoning_effort"'));assert.ok(html.includes('id="vision-reasoning_effort"'));assert.ok(html.includes('id="voice-engine"'));});
test('desktop exposes a narrow bridge and blocks navigation',()=>{const preload=fs.readFileSync(path.join(__dirname,'../preload.js'),'utf8');const main=fs.readFileSync(path.join(__dirname,'../main.js'),'utf8');assert.ok(preload.includes("exposeInMainWorld('minto'"));assert.ok(!preload.includes('chatSendWithImage'));assert.ok(main.includes('contextIsolation:true'));assert.ok(main.includes('nodeIntegration:false'));assert.ok(main.includes("setWindowOpenHandler(()=>({action:'deny'}))"));assert.ok(main.includes('display_id===displayId'));assert.ok(main.includes('setContentProtection(true)'));});
test('chat is hidden until opened and settings provide separate providers and independent saves',()=>{const html=fs.readFileSync(path.join(__dirname,'../renderer/chat.html'),'utf8'),settings=fs.readFileSync(path.join(__dirname,'../renderer/settings.html'),'utf8');assert.ok(fs.readFileSync(path.join(__dirname,'../main.js'),'utf8').includes('show:false,transparent:true'));assert.ok(!fs.readFileSync(path.join(__dirname,'../renderer/index.html'),'utf8').includes('id="chat-panel"'));assert.ok(html.includes('id="chat-history"'));assert.ok(html.includes('id="chat-input"'));for(const id of ['llm-provider','vision-provider','observation-display_id','save-list','save-summary','voice-api_base'])assert.ok(settings.includes('id="'+id+'"'),id);assert.ok(!settings.includes('xuan'));});

