'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events'),path=require('node:path'),{pathToFileURL}=require('node:url');
function load(){try{return require('../services/region-selector');}catch(error){if(error.code!=='MODULE_NOT_FOUND')throw error;return {};}}
function setup(){const handlers=new Map(),windows=[];class Window extends EventEmitter{constructor(options){super();this.options=options;this.webContents=new EventEmitter();this.webContents.setWindowOpenHandler=()=>{};this.webContents.session={setPermissionRequestHandler(){}};windows.push(this);}loadFile(file){this.file=file;}setContentProtection(value){this.protected=value;}setAlwaysOnTop(){}isFocused(){return false;}destroy(){this.emit('closed');}}
 const {RegionSelector}=load();assert.equal(typeof RegionSelector,'function');const selector=new RegionSelector({BrowserWindow:Window,ipcMain:{handle:(channel,handler)=>handlers.set(channel,handler)},root:path.join(__dirname,'..')});
 const display={id:41,bounds:{x:-1920,y:0,width:1920,height:1080}},ui={language:'ja',font_family:'Yu Gothic',font_size:16};return {selector,handlers,windows,display,ui,event:window=>({sender:window.webContents,senderFrame:{url:pathToFileURL(path.join(__dirname,'../renderer/region.html')).href}})};
}
test('selector returns the exact selected display region and releases its window',async()=>{const app=setup(),pending=app.selector.select(app.display,app.ui),window=app.windows[0];assert.equal(window.options.x,-1920);assert.equal(window.protected,true);assert.equal(app.selector.active,true);const state=await app.handlers.get('minto:region-state')(app.event(window));assert.equal(state.language,'ja');await app.handlers.get('minto:region-complete')(app.event(window),{region_x:.1,region_y:.2,region_width:.3,region_height:.4});const result=await pending;assert.equal(result.cancelled,false);assert.equal(result.observation.display_id,'41');assert.equal(result.observation.capture_mode,'region');assert.equal(app.selector.active,false);});
test('selector rejects unauthorized senders and malformed regions without closing',async()=>{const app=setup(),pending=app.selector.select(app.display,app.ui),window=app.windows[0],event=app.event(window);await assert.rejects(()=>app.handlers.get('minto:region-complete')({...event,sender:{}},{region_x:0,region_y:0,region_width:.5,region_height:.5}));await assert.rejects(()=>app.handlers.get('minto:region-state')({...event,senderFrame:{url:'file:///other.html'}}));await assert.rejects(()=>app.handlers.get('minto:region-complete')(event,{region_x:.8,region_y:0,region_width:.5,region_height:.5}));assert.equal(app.selector.active,true);await app.handlers.get('minto:region-cancel')(event);assert.deepEqual(await pending,{cancelled:true});assert.equal(app.selector.active,false);});
test('closing or cancelling the selector leaves no pending selection',async()=>{const app=setup(),pending=app.selector.select(app.display,app.ui);app.windows[0].destroy();assert.deepEqual(await pending,{cancelled:true});const second=app.selector.select(app.display,app.ui);app.selector.cancel();assert.deepEqual(await second,{cancelled:true});});
test('mouse selection handles reverse dragging and clamps edges with no zero-area result',()=>{let api;try{api=require('../renderer/region');}catch(error){if(error.code!=='MODULE_NOT_FOUND')throw error;api={};}assert.equal(typeof api.normalizedSelection,'function');assert.deepEqual(api.normalizedSelection({x:700,y:600},{x:100,y:200},1000,1000),{region_x:.1,region_y:.2,region_width:.6,region_height:.4});assert.deepEqual(api.normalizedSelection({x:-100,y:-100},{x:2000,y:2000},1000,1000),{region_x:0,region_y:0,region_width:1,region_height:1});assert.throws(()=>api.normalizedSelection({x:1,y:1},{x:1,y:1},1000,1000));});
