'use strict';
const fs=require('node:fs');const path=require('node:path');const {atomicWrite}=require('./save-store');
const PROVIDERS=Object.freeze(['DeepSeek','OpenAI','Gemini','Grok','custom']);
const {validateRegion}=require('./screen-region');
function defaults(){return {version:1,ui:{language:'zh-CN',launch_at_login:false,font_family:'Microsoft YaHei',font_size:14},llm:{provider:'custom',api_base:'',api_key:'',model:'',reasoning_effort:'high',multimodal:false},vision:{provider:'custom',api_base:'',api_key:'',model:'',reasoning_effort:'high'},voice:{enabled:true,engine:'bundled',api_base:'http://127.0.0.1:5000',model_id:'0',speaker_name:'',style:'',length:1,style_weight:1},observation:{enabled:false,display_id:'',interval_seconds:60,cooldown_seconds:120,capture_mode:'screen',region_x:0,region_y:0,region_width:0,region_height:0}};}
class SettingsStore{
 constructor(root,secure){this.file=path.join(root,'settings.json');this.secure=secure;this.value=defaults();if(fs.existsSync(this.file)){const data=JSON.parse(fs.readFileSync(this.file,'utf8'));if(data.version!==1)throw new Error('设置文件版本不支持');for(const group of ['ui','llm','vision','voice','observation'])if(data[group])Object.assign(this.value[group],data[group]);for(const group of ['llm','vision']){const encrypted=this.value[group].api_key;this.value[group].api_key=encrypted?secure.decryptString(Buffer.from(encrypted,'base64')):'';}}}
 public(){const data=structuredClone(this.value);for(const group of ['llm','vision']){data[group].key_configured=Boolean(data[group].api_key);delete data[group].api_key;}return data;}
 update(input){if(!input||Array.isArray(input)||typeof input!=='object')throw new Error('设置格式无效');const next=structuredClone(this.value);for(const group of Object.keys(input)){if(!['ui','llm','vision','voice','observation'].includes(group)||!input[group]||Array.isArray(input[group])||typeof input[group]!=='object')throw new Error('未知设置字段');for(const [key,value]of Object.entries(input[group])){if(!Object.hasOwn(next[group],key))throw new Error('未知设置字段');if(typeof value!==typeof next[group][key])throw new Error('设置字段类型不匹配');if(typeof value==='string'&&value.length>12000)throw new Error('设置字段过长');next[group][key]=value;}}
 if(!['zh-CN','ja','en'].includes(next.ui.language))throw new Error('界面语言无效');if(!next.ui.font_family.trim()||next.ui.font_family.length>120||/[\x00-\x1f\x7f"\\;{}<>]/u.test(next.ui.font_family))throw new Error('字体名称无效');if(!Number.isFinite(next.ui.font_size)||next.ui.font_size<10||next.ui.font_size>28)throw new Error('字号须在 10 到 28 之间');validateRegion(next.observation);for(const group of ['llm','vision']){if(!PROVIDERS.includes(next[group].provider))throw new Error('服务类型无效');if(!['low','medium','high','max'].includes(next[group].reasoning_effort))throw new Error('思考深度无效');}if(!['bundled','external'].includes(next.voice.engine))throw new Error('语音运行方式无效');for(const group of ['llm','vision','voice'])if(next[group].api_base){const url=new URL(next[group].api_base);if(!['https:','http:'].includes(url.protocol)||url.username||url.password)throw new Error('服务地址须为 HTTP 或 HTTPS，且不能包含凭据');}
 for(const [key,min,max]of [['interval_seconds',10,3600],['cooldown_seconds',120,86400]])if(!Number.isFinite(next.observation[key])||next.observation[key]<min||next.observation[key]>max)throw new Error('观测时间超出范围');for(const key of ['length','style_weight'])if(!Number.isFinite(next.voice[key])||next.voice[key]<0.1||next.voice[key]>5)throw new Error('语音参数超出范围');const disk=structuredClone(next);for(const group of ['llm','vision']){if(disk[group].api_key&&!this.secure.isEncryptionAvailable())throw new Error('系统密钥加密不可用，未保存 API 密钥');disk[group].api_key=disk[group].api_key?this.secure.encryptString(disk[group].api_key).toString('base64'):'';}atomicWrite(this.file,disk);this.value=next;return this.public();
 }
}
module.exports={SettingsStore,PROVIDERS};
